# Problem 1
import turtle

t = turtle.Turtle()
t.pencolor('red')
t.speed(1)
t.pensize(1)
t.circle(1)
t.circle(3)
t.circle(5)
t.circle(10)
t.circle(15)
t.circle(20)
t.circle(25)
t.circle(30)
t.circle(35)
t.circle(40)
t.circle(48)
t.circle(58)
t.circle(68)
t.circle(76)
t.circle(80)
t.circle(90)
t.circle(100)
#last problem
import turtle as t
import random as r
xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()
xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()

xcolors = ["red", "yellow", "green", "blue", "purple", "orange", "black", "red", "yellow", "green", "blue", "purple", "orange"]
I_LIKE_TO_EAT = r.choice(xcolors)
t.begin_fill()
t.fillcolor(I_LIKE_TO_EAT)
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.left(5)
t.end_fill()
print("teacher this homework is so hard")
t.circle(110)
t.circle(120)
t.circle(130)
t.circle(140)
t.circle(150)
turtle.done()
print("You Like it")
# Problem 2
